baseURL = 'https://bowen.pims.math.ca/'
languageCode = 'en-us'
title = "Rufus Bowen's Notebook"
theme = 'ananke'

[taxonomies]
  tag = 'tags'

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
  block = [['\[', '\]'], ['$$', '$$']]
  inline = [['\(', '\)'], ['$', '$']]
[params]
  custom_css = ["custom.css","glightbox.min.css"]
  math = true
  background_color_class = "bg-dark-blue"
  read_more_copy = "View this problem"
  site_log = "images/logo.svg"

[menus]
  [[menus.main]]
    name = 'Problems'
    pageRef = '/problem/'
    weight = 10
  [[menus.main]]
    name = 'Bibliography'
    pageRef = '/biblio/'
    weight = 20
  [[menus.main]]
    name = 'Gallery'
    pageRef = '/notebook/'
    weight = 30

